### ISSUE TITLE
На какъв език да създаваме issues?

### ISSUE THREAD

**Issue by danielng01** [governmentbg/about#2]
На какъв език да създаваме issues?
In what language to create issues?

Супер сте. Това е най-хубавото нещо, което се е случвало последните години тук в България

**Comment by mitio** [comment]
Няма стриктна конвенция за това все още.

В общите хранилища с описания, които са на български, вероятно на български
ще е по-удобно, тъй като вече има доста текст на този език.

Аз бих избрал английски само в хранилища, които са с по-технически проекти,
за които има голяма перспектива за reuse в международен контекст.

Но на който и от двата езика да е, все ще се намери кой да отговори :)

**Comment by danielng01** [comment]
Пиши го Fixed
