### ISSUE TITLE
Спрени issues за repositories

### ISSUE THREAD

**Issue by danielng01** [governmentbg/about#3]
Тук никъде не видях issues tab
https://github.com/governmentbg/ckan-bulgarian-theme
а примерно исках да кажа, че липсва лицензно споразумение

Възможен начин за fix
https://help.github.com/articles/disabling-issues/

**Comment by danielng01** [comment]
Тук също
https://github.com/governmentbg/ckan

**Comment by danielng01** [comment]
И тук 
https://github.com/governmentbg/data-viz
https://github.com/governmentbg/ckan-datapusher

**Comment by mitio** [comment]
@danielng01 благодаря за напомнянето, issues вече са активирани във всички посочени хранилища.

Причината да ги бяхме спрели първоначално е, че координираме проблемите, свързани със сайта на портала за отворени данни, в [това мета-хранилище](https://github.com/governmentbg/opendata) и искахме да намалим вероятността за объркване.

Въпреки това, смятам, че е по-добра идея всяко хранилище да си има място за issues и ако има нужда от по-специални правила в тези issues, може да се сложи `CONTRIBUTING.md`, който обяснява правилата и дава съответните насоки.

Считам този проблем за решен, но ако има нужда, отвори пак issue-то.
